name: Build Plugin for Atlassian Jira
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: configure JDK version and provider
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: build Atlassian Jira plugin
        run: mvn clean package
      - run: mkdir plugin && cp entity-mapper-plugin/target/entity-mapper-plugin-2.0.1-SNAPSHOT.jar plugin
      - uses: actions/upload-artifact@v4
        with:
          name: Plugin
          path: plugin